name: 'Terraform'

on:
  push:
    branches:
      - main
    # paths:
    #   - 'servicebus/**'
    #   - 'elasticsearch/**'  
env:
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}      

jobs:
  changed_dirs:
    runs-on: ubuntu-latest
    outputs:
      run_sb: ${{ steps.check_servicebus.outputs.run_servicebus }}
      run_es: ${{ steps.check_elasticsearch.outputs.run_elasticsearch }} 
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      - name: Get dir changes
        id: check_dirs
        uses: tj-actions/changed-files@v40
        with:
          files_yaml: |
            servicebus:
              - servicebus/**.tf
            elasticsearch:
              - elasticsearch/**.tf  

      - name: Set up run service bus
        id: check_servicebus
        if: steps.check_dirs.outputs.servicebus_any_changed == 'true'
        run: |
          echo "run_servicebus=true" >> $GITHUB_OUTPUT
      - name: Set up run elastic search
        id: check_elasticsearch
        if: steps.check_dirs.outputs.elasticsearch_any_changed == 'true'
        run: |
          echo "run_elasticsearch=true" >> $GITHUB_OUTPUT    
  servicebus:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'servicebus/')
    needs: changed_dirs
    if: ${{ needs.changed_dirs.outputs.run_sb == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: echo ${{ needs.changed_dirs.outputs.run_sb }} 

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./servicebus

      - name: Terraform Plan
        run: terraform plan  
        working-directory: ./servicebus
      
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply --auto-approve 
        working-directory: ./servicebus  
      # - name: Terraform Destroy
      #   run: terraform destroy --auto-approve 
      #   working-directory: ./servicebus 
  
  elasticsearch:
    runs-on: ubuntu-latest
    # if: github.event_name == 'push' && contains(github.event.head_commit.modified, 'elasticsearch/')
    needs: changed_dirs
    if: ${{ needs.changed_dirs.outputs.run_es == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: echo ${{ needs.changed_dirs.outputs.run_es }}   
        

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./elasticsearch

      - name: Terraform Plan
        if: github.ref == 'refs/heads/main'
        run: terraform plan  
        working-directory: ./elasticsearch

      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/main'
      #   run: terraform apply --auto-approve 
      #   working-directory: ./servicebus  
      
      # - name: Terraform Destroy
      #   run: terraform destroy --auto-approve 
      #   working-directory: ./servicebus 


      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./servicebus
        # env:
        #   ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        #   ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        #   ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        #   ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
