# name: Terraform

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   terraform:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup Terraform
#       uses: hashicorp/setup-terraform@v1

#     - name: Azure Login
#       uses: azure/login@v1
#       with:
#         creds: |
#           {
#             "clientId": "${{ secrets.CLIENT_ID }}",
#             "clientSecret": "${{ secrets.CLIENT_SECRET }}",
#             "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
#             "tenantId": "${{ secrets.TENANT_ID }}"
#             "root_path": '../elasticsearch'
#           }
#     - name: Terraform worklow
#       working-directory: ${{ env.root_path }}
#       run: |
#         terraform init
#         terraform plan
#         terraform apply -auto-approve



name: 'Terraform-action'

on:
  push:
    branches:
      - main
    # paths:
    #   - '**/actions/terraform-azure/**'
  pull_request:
  workflow_dispatch: #this attribute will enable the manual run to the pipeline
  

jobs:
  terraform_plan:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: dev
    env: 
      ROOT_PATH: '../elasticsearch'
      ARM_CLIENT_ID: ${{secrets.CLIENT_ID}}
      ARM_CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: ${{secrets.SUBSCRIPTION_ID}}
      ARM_TENANT_ID: ${{secrets.TENANT_ID}}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
     - name: checkout
       uses: actions/checkout@v2
     - name: terraform
       uses: robertdebock/terraform-action@1.1.2
       with:
          action: init
          directory: ${{env.ROOT_PATH}}
    
     - name: terraform plan
       uses: robertdebock/terraform-action@1.1.2
       with:
          action: plan
          directory: ${{env.ROOT_PATH}}

     - name: terraform apply
       uses: robertdebock/terraform-action@1.1.2
       with:
          action: plan
          directory: ${{env.ROOT_PATH}}