name: 'Terraform'

on:
  push:
    branches:
      - main
env:
  ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}      

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./elasticsearch

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./elasticsearch


      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./elasticsearch
        # env:
        #   ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        #   ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        #   ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        #   ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
