name: 'Terraform'

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "tenantId": "${{ secrets.TENANT_ID }}",
              "subscriptionId": "${{ secrets.SUBSCRIPTION_ID }}",
              "clientId": "${{ secrets.CLIENT_ID }}",
              "clientSecret": "${{ secrets.CLIENT_SECRET }}"
            }

      - name: Terraform Init
        run: terraform init
        working-directory: ./elasticsearch

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./elasticsearch


      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./elasticsearch
        # env:
        #   ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
        #   ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
        #   ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
        #   ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
